#! /bin/sh
### BEGIN INIT INFO
# Provides:             easyckan_harvest
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Watch for changes on CKAN Harvester datasets
# Description:          Watch for changes on CKAN Harvester datasets
### END INIT INFO

su -c "nohup /etc/easyckan/helpers/harvest.sh gather_consumer";
su -c "nohup /etc/easyckan/helpers/harvest.sh fetch_consumer";